<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
    <name>Migration from JIRA Zephyr to Katalon TestOps</name>
    <description></description>
    <tag></tag>
    <isRerun>false</isRerun>
    <mailRecipient></mailRecipient>
    <numberOfRerun>3</numberOfRerun>
    <pageLoadTimeout>30</pageLoadTimeout>
    <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
    <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
    <rerunImmediately>true</rerunImmediately>
    <testSuiteGuid>bd2a0775-54fd-4ab5-8325-38da22031ac2</testSuiteGuid>
    <testCaseLink>
        <guid>4d875db1-8332-4491-b57a-a2575d2a0dba</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Common Test Cases/Login Medium</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>19fe967b-1564-4705-aff2-848d45b84489</variableId>
        </variableLink>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>75fa3d79-7e92-4d55-b359-f7c9493ea288</variableId>
        </variableLink>
    </testCaseLink>
    <testCaseLink>
        <guid>46ca83d4-3ee8-4a83-b4c7-d163baa33a25</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Main Test Cases/TC7_Verify Successful Skip</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>7c5958cd-510a-4460-9e57-37be62533281</variableId>
        </variableLink>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>fa0352c9-7f7c-4e82-bbf7-7b2a7a586cfb</variableId>
        </variableLink>
    </testCaseLink>
</TestSuiteEntity>
